sonar.projectKey=EcommerceNike
sonar.projectName=Ecommerce Nike API
sonar.sources=src
sonar.tests=src
sonar.exclusions=**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
